#!/bin/bash
sudo rm -Rf ~/.oh-my-zsh
sudo rm ~/.zshrc
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sudo rm -Rf ~/.oh-my-zsh
sudo rm ~/.zshrc
mv .oh-my-zsh ~/
mv .zshrc ~/
